"""Add Slack variables

Revision ID: 02a0ced07cb9
Revises: 072dd2b2d9a5
Create Date: 2020-04-04 11:41:43.788292
44b8cd08fe4a
"""
from alembic import op
import sqlalchemy as sa
import datetime
from app.models import cfg_settings

# revision identifiers, used by Alembic.
revision = '02a0ced07cb9'
down_revision = '072dd2b2d9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    date_created = datetime.datetime.now().isoformat()
    date_modified = datetime.datetime.now().isoformat()

    op.bulk_insert(
        cfg_settings.Cfg_settings.__table__,
        [
            {
                "key": "SLACK_WEBHOOK",
                "value": "",
                "public": True,
                "date_created": date_created,
                "date_modified": date_modified,
                "description": "Slack webhook for posting activity messages."
            },
            {
                "key": "SLACK_POST_WHEN",
                "value": "ARTIFACT_CREATED,ARTIFACT_MODIFIED,COMMENTS,RELEASES_MADE,STATE_TOGGLED",
                "public": True,
                "date_created": date_created,
                "date_modified": date_modified,
                "description": "Comma-separated list of event messages to post to slack. Options are: ARTIFACT_CREATED,ARTIFACT_MODIFIED,COMMENTS,RELEASES_MADE,STATE_TOGGLED"
            },
            {
                "key": "SLACK_EXCLUDE_USERS",
                "value": "",
                "public": True,
                "date_created": date_created,
                "date_modified": date_modified,
                "description": "Comma-separated list of user email addresses to exclude from Slack posts. Useful for service accounts. "
            },
            {
                "key": "SLACK_CHANNEL",
                "value": "#threatkb",
                "public": True,
                "date_created": date_created,
                "date_modified": date_modified,
                "description": "Slack channel to post to."
            },
            {
                "key": "SLACK_USER",
                "value": "ThreatKB",
                "public": True,
                "date_created": date_created,
                "date_modified": date_modified,
                "description": "Slack username messages will appear as."
            },
            {
                "key": "SLACK_TEMPLATE",
                "value": "ACTIVITY_TYPE activity from USER_EMAIL on URL\n\nACTIVITY_TEXT",
                "public": True,
                "date_created": date_created,
                "date_modified": date_modified,
                "description": "Template message to use when posting to Slack. Special variables available for use in the template are: USER_EMAIL, USER_ID, USER_FIRSTNAME, USER_LASTNAME, URL, ACTIVITY_TYPE, ACTIVITY_TEXT, ACTIVITY_TEXT_SHORT, ACTIVITY_DATE, ENTITY_TYPE, ENTITY_ID, ENTITY_NAME"
            },
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    keys = ["SLACK_TEMPLATE", "SLACK_USER", "SLACK_CHANNEL", "SLACK_EXCLUDE_USERS", "SLACK_POST_WHEN", "SLACK_WEBHOOK"]
    for key in keys:
        op.execute("""DELETE from cfg_settings where `key`='%s';""" % (key))

    # ### end Alembic commands ###
