"""Config option for non-admin task visibility

Revision ID: 072dd2b2d9a5
Revises: d5cfdd54cb1f
Create Date: 2019-09-02 16:03:07.978674

"""
import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
from app.models import cfg_settings

revision = '072dd2b2d9a5'
down_revision = 'd5cfdd54cb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    date_created = datetime.datetime.now().isoformat()
    date_modified = datetime.datetime.now().isoformat()

    op.bulk_insert(
        cfg_settings.Cfg_settings.__table__,
        [
            {
                "key": "ENABLE_NON_ADMIN_TASK_VISIBILITY",
                "value": "0",
                "public": True,
                "date_created": date_created,
                "date_modified": date_modified,
                "description": "Tasks are visible to non-admins when enabled."
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    keys = ["ENABLE_NON_ADMIN_TASK_VISIBILITY"]
    for key in keys:
        op.execute("""DELETE from cfg_settings where `key`='%s';""" % key)
    # ### end Alembic commands ###
