"""Get rid of unnecessary metadata in artifacts

Revision ID: 0822c8e4629a
Revises: 14eb52ff5135
Create Date: 2017-12-25 18:09:01.068603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0822c8e4629a'
down_revision = '14eb52ff5135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c2dns', u'reference_link')
    op.drop_column('c2dns', u'description')
    op.drop_column('c2ip', u'reference_link')
    op.drop_column('c2ip', u'description')
    op.drop_column('yara_rules', u'confidence')
    op.drop_column('yara_rules', u'description')
    op.drop_column('yara_rules', u'file_type')
    op.drop_column('yara_rules', u'subcategory2')
    op.drop_column('yara_rules', u'subcategory3')
    op.drop_column('yara_rules', u'subcategory1')
    op.drop_column('yara_rules', u'reference_link')
    op.drop_column('yara_rules', u'test_status')
    op.drop_column('yara_rules', u'severity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yara_rules',
                  sa.Column(u'severity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('yara_rules', sa.Column(u'test_status', mysql.VARCHAR(length=16), nullable=True))
    op.add_column('yara_rules', sa.Column(u'reference_link', mysql.VARCHAR(length=2048), nullable=True))
    op.add_column('yara_rules', sa.Column(u'subcategory1', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('yara_rules', sa.Column(u'subcategory3', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('yara_rules', sa.Column(u'subcategory2', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('yara_rules', sa.Column(u'file_type', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('yara_rules', sa.Column(u'description', mysql.VARCHAR(length=4096), nullable=True))
    op.add_column('yara_rules',
                  sa.Column(u'confidence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('c2ip', sa.Column(u'description', mysql.VARCHAR(length=4096), nullable=True))
    op.add_column('c2ip', sa.Column(u'reference_link', mysql.VARCHAR(length=2048), nullable=True))
    op.add_column('c2dns', sa.Column(u'description', mysql.VARCHAR(length=4096), nullable=True))
    op.add_column('c2dns', sa.Column(u'reference_link', mysql.VARCHAR(length=2048), nullable=True))
    # ### end Alembic commands ###
