"""Get rid of unnecessary metadata in artifacts

Revision ID: 0822c8e4629a
Revises: 14eb52ff5135
Create Date: 2017-12-25 18:09:01.068603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0822c8e4629a'
down_revision = '14eb52ff5135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c2dns', 'reference_link')
    op.drop_column('c2dns', 'description')
    op.drop_column('c2ip', 'reference_link')
    op.drop_column('c2ip', 'description')
    op.drop_column('yara_rules', 'confidence')
    op.drop_column('yara_rules', 'description')
    op.drop_column('yara_rules', 'file_type')
    op.drop_column('yara_rules', 'subcategory2')
    op.drop_column('yara_rules', 'subcategory3')
    op.drop_column('yara_rules', 'subcategory1')
    op.drop_column('yara_rules', 'reference_link')
    op.drop_column('yara_rules', 'test_status')
    op.drop_column('yara_rules', 'severity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yara_rules',
                  sa.Column('severity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('yara_rules', sa.Column('test_status', mysql.VARCHAR(length=16), nullable=True))
    op.add_column('yara_rules', sa.Column('reference_link', mysql.VARCHAR(length=2048), nullable=True))
    op.add_column('yara_rules', sa.Column('subcategory1', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('yara_rules', sa.Column('subcategory3', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('yara_rules', sa.Column('subcategory2', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('yara_rules', sa.Column('file_type', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('yara_rules', sa.Column('description', mysql.VARCHAR(length=4096), nullable=True))
    op.add_column('yara_rules',
                  sa.Column('confidence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('c2ip', sa.Column('description', mysql.VARCHAR(length=4096), nullable=True))
    op.add_column('c2ip', sa.Column('reference_link', mysql.VARCHAR(length=2048), nullable=True))
    op.add_column('c2dns', sa.Column('description', mysql.VARCHAR(length=4096), nullable=True))
    op.add_column('c2dns', sa.Column('reference_link', mysql.VARCHAR(length=2048), nullable=True))
    # ### end Alembic commands ###
