"""Add sig, dns, ip tracking to releases

Revision ID: 0896164f6037
Revises: 658ab905b871
Create Date: 2018-05-16 11:01:28.681080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0896164f6037'
down_revision = '658ab905b871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('num_dns', sa.Integer(), nullable=True))
    op.add_column('releases', sa.Column('num_ips', sa.Integer(), nullable=True))
    op.add_column('releases', sa.Column('num_signatures', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'num_signatures')
    op.drop_column('releases', 'num_ips')
    op.drop_column('releases', 'num_dns')
    # ### end Alembic commands ###
