"""Add is_release_state column to states

Revision ID: 0bd5407cc66d
Revises: 681507459b5d
Create Date: 2017-08-29 11:22:54.441854

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0bd5407cc66d'
down_revision = '681507459b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_states', sa.Column('is_release_state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_states', 'is_release_state')
    # ### end Alembic commands ###
