"""add mitre subtechniques

Revision ID: 0df6e90050b5
Revises: 072dd2b2d9a5
Create Date: 2022-05-14 09:57:42.657840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0df6e90050b5'
down_revision = '072dd2b2d9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yara_rules', sa.Column('_mitre_sub_techniques', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yara_rules__mitre_sub_techniques'), table_name='yara_rules')
    # ### end Alembic commands ###
