"""Add metadata choices

Revision ID: 14eb52ff5135
Revises: 5ccd18d62305
Create Date: 2017-12-25 11:57:14.055185

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '14eb52ff5135'
down_revision = '5ccd18d62305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_choices',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('choice', sa.String(length=512), nullable=False),
                    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('metadata_id', sa.Integer(), nullable=False),
                    sa.Column('created_user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['created_user_id'], ['kb_users.id'], ),
                    sa.ForeignKeyConstraint(['metadata_id'], ['metadata.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_choices')
    # ### end Alembic commands ###
