"""Add owner columns to c2dns, c2ip, yara_rules

Revision ID: 15b203983adb
Revises: f9ebccbd6e12
Create Date: 2017-09-04 11:24:13.773895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b203983adb'
down_revision = 'f9ebccbd6e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c2dns', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'c2dns', 'kb_users', ['owner_user_id'], ['id'])
    op.add_column('c2ip', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'c2ip', 'kb_users', ['owner_user_id'], ['id'])
    op.add_column('yara_rules', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'yara_rules', 'kb_users', ['owner_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yara_rules', type_='foreignkey')
    op.drop_column('yara_rules', 'owner_user_id')
    op.drop_constraint(None, 'c2ip', type_='foreignkey')
    op.drop_column('c2ip', 'owner_user_id')
    op.drop_constraint(None, 'c2dns', type_='foreignkey')
    op.drop_column('c2dns', 'owner_user_id')
    # ### end Alembic commands ###
