"""Add is_active, is_regression to Files

Revision ID: 2ac775fc6e23
Revises: e251ad2f9409
Create Date: 2020-04-06 13:43:52.074753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ac775fc6e23'
down_revision = 'e251ad2f9409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_active', sa.Boolean(), nullable=True, default=True))
    op.create_index(u'ix_files_is_active', 'files', ['is_active'], unique=False)
    op.add_column('files', sa.Column('is_regression', sa.Boolean(), nullable=False, default=True))
    op.create_index(u'ix_files_is_regression', 'files', ['is_regression'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_files_is_regression', table_name='files')
    op.drop_column('files', 'is_regression')
    op.drop_index(u'ix_files_is_active', table_name='files')
    op.drop_column('files', 'is_active')
    # ### end Alembic commands ###
