"""Add description and references to all

Revision ID: 2f0f6d26a505
Revises: d73c420813ea
Create Date: 2018-11-06 21:57:13.576546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f0f6d26a505'
down_revision = 'd73c420813ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c2dns', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('c2dns', sa.Column('references', sa.TEXT(), nullable=True))
    op.add_column('c2ip', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('c2ip', sa.Column('references', sa.TEXT(), nullable=True))
    op.add_column('yara_rules', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('yara_rules', sa.Column('references', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yara_rules', 'references')
    op.drop_column('yara_rules', 'description')
    op.drop_column('c2ip', 'references')
    op.drop_column('c2ip', 'description')
    op.drop_column('c2dns', 'references')
    op.drop_column('c2dns', 'description')
    # ### end Alembic commands ###
