"""adding avg_millis_per_file column to testing_history.

Revision ID: 34f3ffb4d1f1
Revises: ead50264bdf4
Create Date: 2017-08-20 14:54:03.685950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f3ffb4d1f1'
down_revision = 'ead50264bdf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yara_testing_history', sa.Column('avg_millis_per_file', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yara_testing_history', 'avg_millis_per_file')
    # ### end Alembic commands ###
