"""Add first_name, last_name, picture fields to user

Revision ID: 385e63a30f6e
Revises: 8083ff92369f
Create Date: 2017-10-08 20:05:51.624731

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '385e63a30f6e'
down_revision = '8083ff92369f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_users', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('kb_users', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('kb_users', sa.Column('picture', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kb_users', 'picture')
    op.drop_column('kb_users', 'last_name')
    op.drop_column('kb_users', 'first_name')
    # ### end Alembic commands ###
