"""Add active column to tasks table

Revision ID: 38aa862c0a93
Revises: 4fb69d540f6d
Create Date: 2017-09-17 10:17:00.857968

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '38aa862c0a93'
down_revision = '4fb69d540f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'active')
    # ### end Alembic commands ###
