"""adding avg_millis_per_file column to testing_history

Revision ID: 3a3368610e08
Revises: ead50264bdf4
Create Date: 2017-08-20 23:08:26.374145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3368610e08'
down_revision = 'ead50264bdf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yara_testing_history', sa.Column('avg_millis_per_file', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yara_testing_history', 'avg_millis_per_file')
    # ### end Alembic commands ###
