"""adding is_active flag to users.

Revision ID: 3cb9b52b4c5b
Revises: 681507459b5d
Create Date: 2017-09-02 12:41:03.142103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb9b52b4c5b'
down_revision = '681507459b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_users', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kb_users', 'active')
    # ### end Alembic commands ###
