"""added sigature_id column to yara_rules.

Revision ID: 3d325922125f
Revises: bc0fab3363f7
Create Date: 2017-08-13 22:40:43.392676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d325922125f'
down_revision = '44b8cd08fe4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yara_rules', sa.Column('signature_id', sa.Integer(), nullable=False))
    op.create_index('ix_yara_rules_category', 'yara_rules', ['category'], unique=False)
    op.create_index('ix_yara_rules_signature_id', 'yara_rules', ['signature_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_yara_rules_signature_id', table_name='yara_rules')
    op.drop_index('ix_yara_rules_category', table_name='yara_rules')
    op.drop_column('yara_rules', 'signature_id')
    # ### end Alembic commands ###
