"""Release flag for categories

Revision ID: 44b8cd08fe4a
Revises: 072dd2b2d9a5
Create Date: 2019-09-25 23:09:01.660399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44b8cd08fe4a'
down_revision = '072dd2b2d9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_category_range_mapping', sa.Column('include_in_release', sa.Boolean(), nullable=False))
    op.create_index(u'ix_cfg_category_range_mapping_include_in_release', 'cfg_category_range_mapping', ['include_in_release'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_cfg_category_range_mapping_include_in_release', table_name='cfg_category_range_mapping')
    op.drop_column('cfg_category_range_mapping', 'include_in_release')
    # ### end Alembic commands ###
