"""Release flag for categories

Revision ID: 44b8cd08fe4a
Revises: 072dd2b2d9a5
Create Date: 2019-09-25 23:09:01.660399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44b8cd08fe4a'
down_revision = 'bc0fab3363f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_category_range_mapping', sa.Column('include_in_release_notes', sa.Boolean(), nullable=True))
    op.create_index('ix_cfg_category_range_mapping_include_in_release_notes', 'cfg_category_range_mapping',
                    ['include_in_release_notes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cfg_category_range_mapping_include_in_release_notes', table_name='cfg_category_range_mapping')
    op.drop_column('cfg_category_range_mapping', 'include_in_release_notes')
    # ### end Alembic commands ###
