"""unique index on tags and default description templates

Revision ID: 4af97076d0d0
Revises: 0df6e90050b5
Create Date: 2022-05-17 20:33:26.317173

"""
import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from app.models import cfg_settings

# revision identifiers, used by Alembic.
revision = '4af97076d0d0'
down_revision = '0df6e90050b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tags', ['text'])
    date_created = datetime.datetime.now().isoformat()
    date_modified = datetime.datetime.now().isoformat()

    op.bulk_insert(
        cfg_settings.Cfg_settings.__table__,
        [
            {
                "key": "DESCRIPTION_TEMPLATE_C2DNS",
                "value": "This template description will show up; As an option in the UI as a dropdown; Modify this in the settings panel/API",
                "public": True,
                "date_created": date_created,
                "date_modified": date_modified,
                "description": "Template descriptions to use for C2DNS."
            },
            {
                "key": "DESCRIPTION_TEMPLATE_C2IP",
                "value": "This template description will show up; As an option in the UI as a dropdown; Modify this in the settings panel/API",
                "public": True,
                "date_created": date_created,
                "date_modified": date_modified,
                "description": "Template descriptions to use for C2IP."
            },
            {
                "key": "DESCRIPTION_TEMPLATE_YARARULE",
                "value": "This template description will show up; As an option in the UI as a dropdown; Modify this in the settings panel/API",
                "public": True,
                "date_created": date_created,
                "date_modified": date_modified,
                "description": "Template descriptions to use for Yara Rules."
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    keys = ["DESCRIPTION_TEMPLATE_C2DNS", "DESCRIPTION_TEMPLATE_C2IP", "DESCRIPTION_TEMPLATE_YARARULE"]
    for key in keys:
        op.execute("""DELETE from cfg_settings where `key`='%s';""" % (key))

# ### end Alembic commands ###
