"""Artifact Static References 2

Revision ID: 4d75b1621822
Revises: 4e7228ea59d1
Create Date: 2019-04-08 23:21:00.920817

"""
import datetime
from alembic import op

# revision identifiers, used by Alembic.
revision = '4d75b1621822'
down_revision = '4e7228ea59d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    date_modified = datetime.datetime.now().isoformat()
    key = "ARTIFACT_STATIC_REFERENCES"
    value = "{\"DNS\": [{\"name\": \"DomainTools\", \"url\": \"https://whois.domaintools.com/\"},{\"name\": \"VirusTotal\", \"url\": \"https://www.virustotal.com/#/domain/\"},{\"name\": \"PacketTotal\", \"url\": \"https://packettotal.com/app/search?q=\"}],\"IP\": [{\"name\": \"URLScan\", \"url\": \"https://urlscan.io/search/#\"},{\"name\": \"DomainTools\", \"url\": \"https://whois.domaintools.com/\"},{\"name\": \"ReverseIP\", \"url\": \"https://reverseip.domaintools.com/search/?q=\"},{\"name\": \"Shodan\", \"url\": \"https://www.shodan.io/host/\"},{\"name\": \"GreyNoise\", \"url\": \"https://viz.greynoise.io/ip/\"},{\"name\": \"VirusTotal\", \"url\": \"https://www.virustotal.com/#/ip-address/\"},{\"name\": \"PacketTotal\", \"url\": \"https://packettotal.com/app/search?q=\"}]}"
    op.execute("""UPDATE cfg_settings set date_modified='%s', value='%s' where `key`='%s';""" % (date_modified, value, key))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    date_modified = datetime.datetime.now().isoformat()
    key = "ARTIFACT_STATIC_REFERENCES"
    value = "{\"DNS\": [\"https://whois.domaintools.com/\",\"https://www.virustotal.com/#/domain/\"],\"IP\": [\"https://whois.domaintools.com/\",\"https://reverseip.domaintools.com/search/?q=\",\"https://www.shodan.io/host/\",\"https://viz.greynoise.io/ip/\",\"https://www.virustotal.com/#/ip-address/\"]}"
    op.execute("""UPDATE cfg_settings set date_modified='%s', value='%s' where `key`='%s';""" % (date_modified, value, key))
   # ### end Alembic commands ###
