"""Drop expiration type column

Revision ID: 4f5f6f314c20
Revises: 4d75b1621822
Create Date: 2019-04-13 16:10:00.991797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f5f6f314c20'
down_revision = '4d75b1621822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c2dns', u'expiration_type')
    op.drop_column('c2ip', u'expiration_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c2ip', sa.Column(u'expiration_type', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('c2dns', sa.Column(u'expiration_type', mysql.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
