"""Make c2dns.domain_name and c2ip.ip unique

Revision ID: 4fb69d540f6d
Revises: 8d2c133477a2
Create Date: 2017-09-16 10:33:08.599695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fb69d540f6d'
down_revision = '8d2c133477a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_c2dns_domain_name', table_name='c2dns')
    op.create_index('ix_c2dns_domain_name', 'c2dns', ['domain_name'], unique=True)
    op.drop_index('ix_c2ip_ip', table_name='c2ip')
    op.create_index('ix_c2ip_ip', 'c2ip', ['ip'], unique=True)
    op.drop_column('c2ip', 'city')
    op.drop_column('c2ip', 'st')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c2ip', sa.Column('st', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('c2ip', sa.Column('city', mysql.VARCHAR(length=64), nullable=True))
    op.drop_index('ix_c2ip_ip', table_name='c2ip')
    op.create_index('ix_c2ip_ip', 'c2ip', ['ip'], unique=False)
    op.drop_index('ix_c2dns_domain_name', table_name='c2dns')
    op.create_index('ix_c2dns_domain_name', 'c2dns', ['domain_name'], unique=False)
    # ### end Alembic commands ###
