"""Access Keys table.

Revision ID: 5ae0821fdf9e
Revises: ffea56d3fc3f
Create Date: 2017-09-17 23:36:53.659099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae0821fdf9e'
down_revision = 'ffea56d3fc3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'deleted'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['kb_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_keys')
    # ### end Alembic commands ###
