"""Add metadata and metadata mapping

Revision ID: 5ccd18d62305
Revises: bf3d4a7f2f15
Create Date: 2017-12-24 11:48:19.356864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ccd18d62305'
down_revision = 'bf3d4a7f2f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('key', sa.String(length=128), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('artifact_type', sa.Integer(), nullable=False),
                    sa.Column('type_', sa.String(length=128), nullable=False),
                    sa.Column('default', sa.String(length=4096), nullable=True),
                    sa.Column('show_in_table', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('created_user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['created_user_id'], ['kb_users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('metadata_mapping',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('value', sa.String(length=60000), nullable=True),
                    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('metadata_id', sa.Integer(), nullable=False),
                    sa.Column('artifact_id', sa.Integer(), nullable=False),
                    sa.Column('created_user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['artifact_id'], ['metadata.id'], ),
                    sa.ForeignKeyConstraint(['created_user_id'], ['kb_users.id'], ),
                    sa.ForeignKeyConstraint(['metadata_id'], ['metadata.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column(u'scripts', 'interpreter',
                    existing_type=mysql.VARCHAR(length=64),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'scripts', 'interpreter',
                    existing_type=mysql.VARCHAR(length=64),
                    nullable=True)
    op.drop_table('metadata_mapping')
    op.drop_table('metadata')
    # ### end Alembic commands ###
