"""Add is_draft_state to cfg_states

Revision ID: 619d198ab938
Revises: ab418625f369
Create Date: 2018-04-17 13:21:54.159492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '619d198ab938'
down_revision = 'ab418625f369'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('cfg_states', sa.Column('is_staging_state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('cfg_states', 'is_staging_state')
    # ### end Alembic commands ###
