"""Add is_draft_state to cfg_states

Revision ID: 619d198ab938
Revises: ab418625f369
Create Date: 2018-04-17 13:21:54.159492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '619d198ab938'
down_revision = 'ab418625f369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_keys', 'created',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('access_keys', 'deleted',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('c2dns', 'date_created',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('c2dns', 'date_modified',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('c2dns', 'expiration_timestamp',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('c2ip', 'date_created',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('c2ip', 'date_modified',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('c2ip', 'expiration_timestamp',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.add_column('cfg_settings', sa.Column('description', sa.String(length=512), nullable=True))
    op.alter_column('cfg_settings', 'date_created',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('cfg_settings', 'date_modified',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('cfg_settings', 'key',
                    existing_type=mysql.VARCHAR(length=256),
                    type_=sa.String(length=512))
    op.alter_column('cfg_settings', 'public',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=True)
    op.add_column('cfg_states', sa.Column('is_draft_state', sa.Integer(), nullable=True))
    op.alter_column('comments', 'date_created',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('comments', 'date_modified',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('files', 'date_created',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('files', 'date_modified',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('kb_users', 'active',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('kb_users', 'admin',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('kb_users', 'registered_on',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True,
                    existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('metadata', 'active',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('metadata', 'date_created',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('metadata', 'date_modified',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('metadata_choices', 'date_created',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('metadata_choices', 'date_modified',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('metadata_mapping', 'date_created',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('metadata_mapping', 'date_modified',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('releases', 'date_created',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('scripts', 'date_created',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('scripts', 'date_modified',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('tasks', 'active',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('tasks', 'date_created',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('tasks', 'date_modified',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('whitelist', 'created_time',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('whitelist', 'modified_time',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('yara_rules', 'active',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('yara_rules', 'condition',
                    existing_type=mysql.MEDIUMTEXT(),
                    type_=sa.String(length=2048),
                    existing_nullable=True)
    op.alter_column('yara_rules', 'creation_date',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('yara_rules', 'last_revision_date',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('yara_rules', 'strings',
                    existing_type=mysql.MEDIUMTEXT(),
                    type_=sa.String(length=30000),
                    existing_nullable=True)
    op.alter_column('yara_rules_history', 'date_created',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('yara_testing_history', 'end_time',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=False)
    op.alter_column('yara_testing_history', 'start_time',
                    existing_type=sa.DATETIME(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yara_testing_history', 'start_time',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=False)
    op.alter_column('yara_testing_history', 'end_time',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=False)
    op.alter_column('yara_rules_history', 'date_created',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('yara_rules', 'strings',
                    existing_type=sa.String(length=30000),
                    type_=mysql.MEDIUMTEXT(),
                    existing_nullable=True)
    op.alter_column('yara_rules', 'last_revision_date',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('yara_rules', 'creation_date',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('yara_rules', 'condition',
                    existing_type=sa.String(length=2048),
                    type_=mysql.MEDIUMTEXT(),
                    existing_nullable=True)
    op.alter_column('yara_rules', 'active',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.alter_column('whitelist', 'modified_time',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('whitelist', 'created_time',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('tasks', 'date_modified',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('tasks', 'date_created',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('tasks', 'active',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.alter_column('scripts', 'date_modified',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('scripts', 'date_created',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('releases', 'date_created',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('metadata_mapping', 'date_modified',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('metadata_mapping', 'date_created',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('metadata_choices', 'date_modified',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('metadata_choices', 'date_created',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('metadata', 'date_modified',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('metadata', 'date_created',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('metadata', 'active',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.alter_column('kb_users', 'registered_on',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True,
                    existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('kb_users', 'admin',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.alter_column('kb_users', 'active',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.alter_column('files', 'date_modified',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('files', 'date_created',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('comments', 'date_modified',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('comments', 'date_created',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.drop_column('cfg_states', 'is_draft_state')
    op.alter_column('cfg_settings', 'public',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=True)
    op.alter_column('cfg_settings', 'key',
                    existing_type=sa.String(length=512),
                    type_=mysql.VARCHAR(length=256))
    op.alter_column('cfg_settings', 'date_modified',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('cfg_settings', 'date_created',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.drop_column('cfg_settings', 'description')
    op.alter_column('c2ip', 'expiration_timestamp',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('c2ip', 'date_modified',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('c2ip', 'date_created',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('c2dns', 'expiration_timestamp',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('c2dns', 'date_modified',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('c2dns', 'date_created',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('access_keys', 'deleted',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    op.alter_column('access_keys', 'created',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DATETIME(),
                    existing_nullable=True)
    # ### end Alembic commands ###
