"""change release data to blob

Revision ID: 658ab905b871
Revises: faa23ce8d2c5
Create Date: 2018-04-29 11:46:41.528373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '658ab905b871'
down_revision = 'faa23ce8d2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('_release_data', mysql.LONGBLOB(), nullable=True))
    op.drop_column('releases', 'release_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('release_data', mysql.LONGTEXT(), nullable=True))
    op.drop_column('releases', '_release_data')
    # ### end Alembic commands ###
