"""makes entity type and id nullable in files

Revision ID: 681507459b5d
Revises: 2a30c4968d80
Create Date: 2017-08-22 23:27:59.458389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '681507459b5d'
down_revision = '2a30c4968d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'entity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('files', 'entity_type',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'entity_type',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('files', 'entity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
