"""Add sha1, sha256, md5 to files table

Revision ID: 705e48818ad8
Revises: 34d5b6b940a7
Create Date: 2017-11-19 18:12:18.378072

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '705e48818ad8'
down_revision = '34d5b6b940a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('md5', sa.String(length=32), nullable=True))
    op.add_column('files', sa.Column('sha1', sa.String(length=40), nullable=True))
    op.add_column('files', sa.Column('sha256', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'sha256')
    op.drop_column('files', 'sha1')
    op.drop_column('files', 'md5')
    # ### end Alembic commands ###
