"""New Macros Table.

Revision ID: 71b6e5811cc8
Revises: 4f5f6f314c20
Create Date: 2019-04-28 14:42:23.533491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71b6e5811cc8'
down_revision = '4f5f6f314c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macros',
                    sa.Column('tag', sa.String(length=512), nullable=False),
                    sa.Column('value', sa.TEXT(), nullable=True),
                    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('tag')
                    )
    op.create_index(u'ix_macros_tag', 'macros', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_macros_tag', table_name='macros')
    op.drop_table('macros')
    # ### end Alembic commands ###
