"""Change date_modified, date_created

Revision ID: 76ac9b0bf6e7
Revises: 922e996462ab
Create Date: 2017-10-21 21:53:49.002787

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '76ac9b0bf6e7'
down_revision = '922e996462ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yara_rules', sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('yara_rules', sa.Column('last_revision_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('yara_rules', 'date_created')
    op.drop_column('yara_rules', 'date_modified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yara_rules', sa.Column('date_modified', sa.DATETIME(), nullable=True))
    op.add_column('yara_rules', sa.Column('date_created', sa.DATETIME(), nullable=True))
    op.drop_column('yara_rules', 'last_revision_date')
    op.drop_column('yara_rules', 'creation_date')
    # ### end Alembic commands ###
