"""add description to cfg_settings

Revision ID: 838898d63a85
Revises: c8aec30b37d4
Create Date: 2018-03-12 22:08:04.998913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '838898d63a85'
down_revision = 'c8aec30b37d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_settings', sa.Column('description', sa.TEXT, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_settings', 'description')
    # ### end Alembic commands ###
