"""tasks model

Revision ID: 8d2c133477a2
Revises: 8a40de624788
Create Date: 2017-09-10 14:04:18.169601

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8d2c133477a2'
down_revision = '8a40de624788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('state', sa.String(length=32), nullable=True),
                    sa.Column('title', sa.String(length=256), nullable=True),
                    sa.Column('description', sa.String(length=2048), nullable=True),
                    sa.Column('final_artifact', sa.String(length=4096), nullable=True),
                    sa.Column('created_user_id', sa.Integer(), nullable=False),
                    sa.Column('modified_user_id', sa.Integer(), nullable=False),
                    sa.Column('owner_user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['created_user_id'], ['kb_users.id'], ),
                    sa.ForeignKeyConstraint(['modified_user_id'], ['kb_users.id'], ),
                    sa.ForeignKeyConstraint(['owner_user_id'], ['kb_users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(u'ix_tasks_description', 'tasks', ['description'], unique=False)
    op.create_index(u'ix_tasks_state', 'tasks', ['state'], unique=False)
    op.create_index(u'ix_tasks_title', 'tasks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_tasks_title', table_name='tasks')
    op.drop_index(u'ix_tasks_state', table_name='tasks')
    op.drop_index(u'ix_tasks_description', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
