"""Get rid of reference text

Revision ID: 922e996462ab
Revises: 385e63a30f6e
Create Date: 2017-10-21 11:05:53.177959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '922e996462ab'
down_revision = '385e63a30f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'cfg_reference_text_templates')
    op.drop_column('c2dns', u'reference_text')
    op.drop_column('c2ip', u'reference_text')
    op.drop_column('yara_rules', u'reference_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yara_rules', sa.Column(u'reference_text', mysql.VARCHAR(length=2048), nullable=True))
    op.add_column('c2ip', sa.Column(u'reference_text', mysql.VARCHAR(length=2048), nullable=True))
    op.add_column('c2dns', sa.Column(u'reference_text', mysql.VARCHAR(length=2048), nullable=True))
    op.create_table(u'cfg_reference_text_templates',
                    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
                    sa.Column(u'template_text', mysql.VARCHAR(length=2048), nullable=True),
                    sa.PrimaryKeyConstraint(u'id'),
                    mysql_default_charset=u'latin1',
                    mysql_engine=u'InnoDB'
                    )
    # ### end Alembic commands ###
