"""adding revision column to yara_rule and yara_rules_history table

Revision ID: 960676c435b2
Revises: cb108888af0b
Create Date: 2017-08-08 22:31:12.096846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960676c435b2'
down_revision = 'cb108888af0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yara_rules_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('rule_json', sa.Text(), nullable=False),
    sa.Column('yara_rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['kb_users.id'], ),
    sa.ForeignKeyConstraint(['yara_rule_id'], ['yara_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('yara_rules', sa.Column('revision', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yara_rules', 'revision')
    op.drop_table('yara_rules_history')
    # ### end Alembic commands ###
