"""Change signature_id to eventid

Revision ID: 9aadb08451dc
Revises: 5ae0821fdf9e
Create Date: 2017-09-30 17:58:53.394735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9aadb08451dc'
down_revision = '5ae0821fdf9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yara_rules', sa.Column('eventid', sa.Integer(), nullable=False))
    op.create_index(u'ix_yara_rules_eventid', 'yara_rules', ['eventid'], unique=False)
    op.drop_index(u'ix_yara_rules_signature_id', table_name=u'yara_rules')
    op.drop_column('yara_rules', u'signature_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yara_rules',
                  sa.Column(u'signature_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_index(u'ix_yara_rules_signature_id', u'yara_rules', [u'signature_id'], unique=False)
    op.drop_index(u'ix_yara_rules_eventid', table_name='yara_rules')
    op.drop_column('yara_rules', 'eventid')
    # ### end Alembic commands ###
