"""adding description to ip and dns

Revision ID: 9ada96d00858
Revises: 0e2074fb38e8
Create Date: 2017-11-02 21:58:04.359548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ada96d00858'
down_revision = '0e2074fb38e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c2dns', sa.Column('description', sa.String(length=4096), nullable=True))
    op.add_column('c2ip', sa.Column('description', sa.String(length=4096), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c2ip', 'description')
    op.drop_column('c2dns', 'description')
    # ### end Alembic commands ###
