"""add release yara rule history

Revision ID: a688cf44cd8a
Revises: a844d4d82d9d
Create Date: 2022-05-23 11:51:00.956023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a688cf44cd8a'
down_revision = 'a844d4d82d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_yara_rule_history',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('yara_rules_history_id', sa.Integer(), nullable=False),
                    sa.Column('release_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
                    sa.ForeignKeyConstraint(['yara_rules_history_id'], ['yara_rules_history.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_release_yara_rule_history_release_id'), 'release_yara_rule_history', ['release_id'],
                    unique=False)
    op.create_index(op.f('ix_release_yara_rule_history_yara_rules_history_id'), 'release_yara_rule_history',
                    ['yara_rules_history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_yara_rule_history_yara_rules_history_id'), table_name='release_yara_rule_history')
    op.drop_index(op.f('ix_release_yara_rule_history_release_id'), table_name='release_yara_rule_history')
    op.drop_table('release_yara_rule_history')
    # ### end Alembic commands ###
