"""directory functionality in files

Revision ID: a844d4d82d9d
Revises: 4af97076d0d0
Create Date: 2022-05-18 18:11:08.028247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a844d4d82d9d'
down_revision = '4af97076d0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('parent_sha256', sa.String(length=64), nullable=True))
    op.add_column('files', sa.Column('parent_md5', sa.String(length=32), nullable=True))
    op.add_column('files', sa.Column('parent_sha1', sa.String(length=40), nullable=True))
    op.add_column('files', sa.Column('path', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'path')
    op.drop_column('files', 'parent_md5')
    op.drop_column('files', 'parent_sha256')
    op.drop_column('files', 'parent_sha1')
    # ### end Alembic commands ###
