"""Add is_retired_state to cfg_states

Revision ID: ab418625f369
Revises: 838898d63a85
Create Date: 2018-04-16 23:48:34.539875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab418625f369'
down_revision = '838898d63a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_states', sa.Column('is_retired_state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_states', 'is_retired_state')
    # ### end Alembic commands ###
