"""add errors

Revision ID: ae93b3e95444
Revises: 8d1a65d94f4b
Create Date: 2018-10-03 22:27:20.064066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae93b3e95444'
down_revision = '8d1a65d94f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('stacktrace', sa.TEXT(), nullable=True),
                    sa.Column('route', sa.String(length=1024), nullable=True),
                    sa.Column('method', sa.String(length=16), nullable=True),
                    sa.Column('remote_addr', sa.String(length=32), nullable=True),
                    sa.Column('args', sa.TEXT(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['kb_users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('error')
    # ### end Alembic commands ###
