"""Changing tags mapping enums.

Revision ID: b315f76a9a56
Revises: 2221286081e8
Create Date: 2017-08-06 19:42:21.467729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b315f76a9a56'
down_revision = '2221286081e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tags_mapping", "source_table", existing_type=mysql.ENUM('c2dns', 'c2ip', 'yara_rule'),
                    type_=mysql.ENUM('c2dns', 'c2ip', 'yara_rules'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tags_mapping", "source_table", existing_type=mysql.ENUM('c2dns', 'c2ip', 'yara_rules'),
                    type_=mysql.ENUM('c2dns', 'c2ip', 'yara_rule'))
    # ### end Alembic commands ###
