"""Add config

Revision ID: b5357371ee6d
Revises: 2221286081e8
Create Date: 2017-08-18 12:08:01.045976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5357371ee6d'
down_revision = '2221286081e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('key', sa.String(length=256), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('value', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_config_key', 'config', ['key'], unique=False)
    op.create_index('ix_config_public', 'config', ['public'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(u'ix_config_public', table_name='config')
    # op.drop_index(u'ix_config_key', table_name='config')
    op.drop_table('config')
    # ### end Alembic commands ###
