"""Add creation creation_date to tags and tags_mapping

Revision ID: bb5b9def8598
Revises: 2ac775fc6e23
Create Date: 2020-12-05 11:54:42.495597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb5b9def8598'
down_revision = '2ac775fc6e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tags_mapping', sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags_mapping', 'creation_date')
    op.drop_column('tags', 'creation_date')
    # ### end Alembic commands ###
