"""tags index

Revision ID: c36406bbd63a
Revises: 65e3f200abd3
Create Date: 2025-05-19 15:08:43.133490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c36406bbd63a'
down_revision = '65e3f200abd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create index for tags_mapping table
    op.create_index('ix_tags_mapping_source', 'tags_mapping',
                    ['source_id', 'source_table'])

    # Create index for tags table
    op.create_index('ix_tags_text', 'tags', ['text'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove indexes in reverse order
    op.drop_index('ix_tags_text', table_name='tags')
    op.drop_index('ix_tags_mapping_source', table_name='tags_mapping')

    # ### end Alembic commands ###
