"""tags index

Revision ID: c36406bbd63a
Revises: 65e3f200abd3
Create Date: 2025-05-19 15:08:43.133490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c36406bbd63a'
down_revision = '65e3f200abd3'
branch_labels = None
depends_on = None


def index_exists(connection, table_name, index_name):
    query = text("""
        SELECT COUNT(1) 
        FROM information_schema.statistics 
        WHERE table_schema = DATABASE() 
        AND table_name = :table_name 
        AND index_name = :index_name
    """)
    result = connection.execute(
        query,
        {"table_name": table_name, "index_name": index_name}
    ).scalar()
    return bool(result)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    # Create index for tags_mapping table
    if not index_exists(connection, 'tags_mapping', 'ix_tags_mapping_source'):
        op.create_index('ix_tags_mapping_source', 'tags_mapping',
                        ['source_id', 'source_table'])


    # Create index for tags table with length limit of 191
    # 191 * 4 bytes (utf8mb4) = 764 bytes, which is under the 767 byte limit
    if not index_exists(connection, 'tags', 'ix_tags_text'):
        op.create_index('ix_tags_text', 'tags', ['text'],
                        mysql_length=191)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    # Check and remove indexes in reverse order
    if index_exists(connection, 'tags', 'ix_tags_text'):
        op.drop_index('ix_tags_text', table_name='tags')

    if index_exists(connection, 'tags_mapping', 'ix_tags_mapping_source'):
        op.drop_index('ix_tags_mapping_source', table_name='tags_mapping')

    # ### end Alembic commands ###
