"""add required column to metadata table

Revision ID: c5b6185beb4c
Revises: 0822c8e4629a
Create Date: 2017-12-25 19:38:40.830662

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c5b6185beb4c'
down_revision = '0822c8e4629a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata', sa.Column('required', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata', 'required')
    # ### end Alembic commands ###
