"""changing registered_on attributes.

Revision ID: d59c15bea7a6
Revises: 3cb9b52b4c5b
Create Date: 2017-09-03 16:52:10.630099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59c15bea7a6'
down_revision = '3cb9b52b4c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kb_users', 'registered_on',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kb_users', 'registered_on',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
