"""New setting for macro tag template

Revision ID: d5cfdd54cb1f
Revises: 6f68d5b06411
Create Date: 2019-04-28 22:19:05.831932

"""
import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from app.models import cfg_settings

# revision identifiers, used by Alembic.
revision = 'd5cfdd54cb1f'
down_revision = '6f68d5b06411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    date_created = datetime.datetime.now().isoformat()
    date_modified = datetime.datetime.now().isoformat()

    op.bulk_insert(
        cfg_settings.Cfg_settings.__table__,
        [
            {
                "key": "MACRO_TAG_TEMPLATE",
                "value": "[[%s]]",
                "public": True,
                "date_created": date_created,
                "date_modified": date_modified,
                "description": "Template used for Macro tags."
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    keys = ["MACRO_TAG_TEMPLATE"]
    for key in keys:
        op.execute("""DELETE from cfg_settings where `key`='%s';""" % (key))

    # ### end Alembic commands ###
