"""change rule_json to large binary

Revision ID: d73c420813ea
Revises: ae93b3e95444
Create Date: 2018-10-23 20:31:42.304996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd73c420813ea'
down_revision = 'ae93b3e95444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yara_rules_history', sa.Column('_rule_json', sa.LargeBinary(), nullable=False))
    op.drop_column('yara_rules_history', 'rule_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yara_rules_history', sa.Column('rule_json', mysql.TEXT(), nullable=False))
    op.drop_column('yara_rules_history', '_rule_json')
    # ### end Alembic commands ###
