"""Add created_user_id to tags and tags_mapping

Revision ID: e38a6dd5da77
Revises: bb5b9def8598
Create Date: 2020-12-05 12:02:10.094898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e38a6dd5da77'
down_revision = 'bb5b9def8598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('created_user_id', sa.Integer()))
    op.add_column('tags_mapping', sa.Column('created_user_id', sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags_mapping', 'created_user_id')
    op.drop_column('tags', 'created_user_id')
    # ### end Alembic commands ###
