"""Config option for batch edits.

Revision ID: e3e2b7dc1b4c
Revises: 072dd2b2d9a5
Create Date: 2021-09-02 22:56:06.203272

"""
import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
from app.models import cfg_settings

revision = 'e3e2b7dc1b4c'
down_revision = '072dd2b2d9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    date_created = datetime.datetime.now().isoformat()
    date_modified = datetime.datetime.now().isoformat()

    op.bulk_insert(
        cfg_settings.Cfg_settings.__table__,
        [
            {
                "key": "BATCH_EDIT_CONFIGURATION",
                "value": "{\"c2ip\" : [\"description\", \"tags\", \"state\", \"owner_user\", \"expiration_timestamp\"]}",
                "public": True,
                "date_created": date_created,
                "date_modified": date_modified,
                "description": "Configuration for which tables and fields are batch editable."
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    keys = ["BATCH_EDIT_CONFIGURATION"]
    for key in keys:
        op.execute("""DELETE from cfg_settings where `key`='%s';""" % key)
    # ### end Alembic commands ###
