"""Add export with release column

Revision ID: ee0d67b4e552
Revises: c5b6185beb4c
Create Date: 2018-01-13 11:13:22.722140

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ee0d67b4e552'
down_revision = 'c5b6185beb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata', sa.Column('export_with_release', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata', 'export_with_release')
    # ### end Alembic commands ###
