"""state for yara rule revisions

Revision ID: faa23ce8d2c5
Revises: 619d198ab938
Create Date: 2018-04-17 14:25:48.906841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'faa23ce8d2c5'
down_revision = '619d198ab938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yara_rules_history', sa.Column('state', sa.String(length=32), nullable=True))
    op.create_index(u'ix_yara_rules_history_state', 'yara_rules_history', ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_yara_rules_history_state', table_name='yara_rules_history')
    op.drop_column('yara_rules_history', 'state')
    # ### end Alembic commands ###
