"""Artifact Static References

Revision ID: fe5820317f46
Revises: 650b0ad88d25
Create Date: 2019-03-30 23:29:48.344330

"""
import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
from app.models import cfg_settings

revision = 'fe5820317f46'
down_revision = '650b0ad88d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    date_created = datetime.datetime.now().isoformat()
    date_modified = datetime.datetime.now().isoformat()

    op.bulk_insert(
        cfg_settings.Cfg_settings.__table__,
        [
            {
                "key": "ARTIFACT_STATIC_REFERENCES",
                "value": "{\"DNS\": [\"https://whois.domaintools.com/\",\"https://www.virustotal.com/#/domain/openrce.org\"],\"IP\": [\"https://whois.domaintools.com/\",\"https://reverseip.domaintools.com/search/?q=\",\"https://www.shodan.io/host/\",\"https://viz.greynoise.io/ip/\",\"https://www.virustotal.com/#/ip-address/\"]}",
                "public": True,
                "date_created": date_created,
                "date_modified": date_modified,
                "description": "Links of Static References for Artifacts."
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    keys = ["ARTIFACT_STATIC_REFERENCES"]
    for key in keys:
        op.execute("""DELETE from cfg_settings where `key`='%s';""" % (key))

    # ### end Alembic commands ###
